
on:
  pull_request:
  push:

jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v4
      id: set-result
      with:
        script: console.log(context); return "Hello!";
        result-encoding: string
